### ISSUE TITLE
ReferenceError: res is not defined

### ISSUE THREAD

**Issue by nicolaje** [benoit-tk/homebridge_thekeys#3]
Hi,

since the last Homebridge update I have this error preventing the The Keys plugin from working :

> [5/17/2020, 7:53:24 PM] Homebridge is running on port 51965.
[5/17/2020, 7:53:29 PM] [TK Maison] check lockers
[5/17/2020, 7:53:29 PM] ReferenceError: res is not defined
    at Request._callback (/usr/local/lib/node_modules/homebridge-thekeys/index.js:50:35)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/17/2020, 7:53:29 PM] Got SIGTERM, shutting down Homebridge...
[5/17/2020, 7:53:34 PM] [TK Maison] check lockers
[5/17/2020, 7:53:34 PM] ReferenceError: res is not defined
    at Request._callback (/usr/local/lib/node_modules/homebridge-thekeys/index.js:50:35)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/17/2020, 7:53:34 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/17/2020, 7:53:39 PM] [HB Supervisor] Restarting Homebridge...
[5/17/2020, 7:53:39 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[5/17/2020, 7:53:39 PM] [HB Supervisor] Started Homebridge v1.0.4 with PID: 27889
[5/17/2020, 7:53:39 PM] Loaded config.json with 1 accessories and 1 platforms.
[5/17/2020, 7:53:39 PM] ---
[5/17/2020, 7:53:40 PM] Loaded plugin: homebridge-config-ui-x
[5/17/2020, 7:53:40 PM] Registering platform 'homebridge-config-ui-x.config'
[5/17/2020, 7:53:40 PM] ---
[5/17/2020, 7:53:40 PM] Loaded plugin: homebridge-thekeys
[5/17/2020, 7:53:40 PM] Registering accessory 'homebridge-thekeys.TheKeys'
[5/17/2020, 7:53:40 PM] ---
[5/17/2020, 7:53:40 PM] Loading 1 platforms...
[5/17/2020, 7:53:40 PM] [Config] Initializing config platform...
[5/17/2020, 7:53:40 PM] [Config] Running in Service Mode
[5/17/2020, 7:53:40 PM] Loading 1 accessories...
[5/17/2020, 7:53:40 PM] [TK Maison] Initializing TheKeys accessory...
[5/17/2020, 7:53:40 PM] [TK Maison] Create new instance of TK accessory
[5/17/2020, 7:53:40 PM] [TK Maison] Starting a TK locker device with name 'TK Maison'...
[5/17/2020, 7:53:40 PM] [TK Maison] Gateway ip: 192.168.1.76
Setup Payload:
X-HM://XXXXXXXXXXX
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by quizatsaderac** [comment]
Hello, i have the same problem with this plugin !

[The Keys] current state of maison: 0
[9/1/2020, 14:55:33] ReferenceError: res is not defined
    at Request._callback (/usr/local/lib/node_modules/homebridge-thekeys/index.js:50:35)
    at self.callback (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-thekeys/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:327:22)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[9/1/2020, 14:55:34] Got SIGTERM, shutting down Homebridge...
[9/1/2020, 14:55:34] [salon] INFO - shutdown

**Comment by benoit-tk** [comment]
Just fix it. This was caused by the gateway not answering (busy or invalid configuration). 
In any case, it should not crash.

**Comment by quizatsaderac** [comment]
indeed, I had to disconnect and reconnect the gatway, and now everything is working again! 
thank you.
